KitapciApp/KitapciApp.UI/Areas/Yonetim/Controllers/SatisController.cs
using KitapciApp.DataAccesLayer;
using KitapciApp.EntityLayer;
using KitapciApp.EntityLayer.SepetClasses;
using KitapciApp.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapciApp.UI.Areas.Yonetim.Controllers
{
    [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
    public class SatisController : Controller
    {
        // GET: Yonetim/Satis
        public ActionResult Listele()
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                return View(uow.SatısWork.GetAll());
            }
        }

        public ActionResult SatisDetay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    return View(uow.SatısDetayWork.GetAllWithKitap((int)id));
                }
            }
            return RedirectToAction("Listele");
        }


        public ActionResult Sil(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Satıs satıs = uow.SatısWork.GetItem(id);
                    if (satıs != null)
                    {
                        return View(satıs);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil")]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Satıs satıs = uow.SatısWork.GetItem(id);
                    if (satıs != null)
                    {
                        uow.SatısWork.Remove(satıs);
                        uow.Save();
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }

        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Satıs satıs = uow.SatısWork.GetItem(id);
                    if (satıs != null)
                    {
                        return View(satıs);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Duzenle(int? id, Satıs satıs)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.SatısWork.Update(satıs);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
            }
            ModelState.AddModelError("", "Düzenleme Yapılamadı.");
            return View(satıs);
        }

        public ActionResult SatisEkle()
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                return View(uow.KitapWork.GetAllWithTur());
            }
        }

        public ActionResult SepeteEkle(int? id)
        {
            if (id != null)
            {
                Sepet sepet;
                if (Session["sepet"] != null)
                {
                    sepet = Session["sepet"] as Sepet;
                }
                else
                {
                    sepet = new Sepet();
                }
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kullanıcı kullanıcı = new Kullanıcı();
                    ViewBag.kullanici = TempData["kullanici"];
                    kullanıcı.EPosta = ViewBag.kullanici;
                    string eposta = kullanıcı.EPosta;
                    Kitap kitap = uow.KitapWork.GetItem(id);
                    if (kitap != null)
                    {
                        sepet.Ekle(kitap, eposta);
                        Session["sepet"] = sepet;
                    }
                }

            }

            return RedirectToAction("SatisEkle");
        }

        public ActionResult SepetGoster()
        {
            Sepet sepet;
            if (Session["sepet"] != null)
            {
                sepet = Session["sepet"] as Sepet;
            }
            else
            {
                sepet = new Sepet();
            }
            return View(sepet.Satıs);
        }

        public ActionResult SatisTamamla()
        {
            Sepet sepet;
            if (Session["sepet"] != null)
            {
                sepet = Session["sepet"] as Sepet;
                using(UnitOfWork uow = new UnitOfWork())
                {
                    sepet.Satıs.TarihSaat = DateTime.Now;
                    uow.SatısWork.Add(sepet.Satıs);
                    foreach(var item in sepet.Satıs.Detaylar)
                    {
                        Kitap kitap = uow.KitapWork.GetItem(item.Kitap.Id);
                        kitap.Adet -= item.Adet;
                        uow.KitapWork.Update(kitap);
                    }
                    uow.Save();
                    Session["sepet"] = null;
                }
            }
            return RedirectToAction("SatisEkle");
        }
    }
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/Duzenle.cshtml
@model KitapciApp.EntityLayer.Satıs
@{
    ViewBag.Title = "Satış Düzenle";
}

<h2>Satış Düzenle</h2>

<br />
<br />

@using (Html.BeginForm("Duzenle", "Satis", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.Id, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Id, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.TarihSaat, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.TarihSaat, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ToplamTutar, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.EPosta, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.EPosta, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.SatisDurum, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x => x.SatisDurum, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <a href="@Url.Action("Listele")" class="btn btn-default">İptal</a>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </div>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/Listele.cshtml
@model List<KitapciApp.EntityLayer.Satıs>
@{
    ViewBag.Title = "Satış Listele";
}

<h2>Listele</h2>

<a href="@Url.Action("SatisEkle")" class="btn btn-primary">Satış Ekle</a>

<br />
<br />

<table class="table">
    <tr>
        <th>Id</th>
        <th>Tarih Saat</th>
        <th>Satış Durum</th>
        <th>EPosta</th>
        <th>Toplam Tutar</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.TarihSaat</td>
            <td>@item.SatisDurum</td>
            <td>@item.EPosta</td>
            <td>@item.ToplamTutar</td>
            <td>
                <a href="@Url.Action("Duzenle", new { id = item.Id})" class="btn btn-warning btn-xs">Düzenle</a>
                <a href="@Url.Action("Sil", new { id = item.Id})" class="btn btn-danger btn-xs">Sil</a>
                <a href="@Url.Action("SatisDetay", new { id = item.Id})" class="btn btn-info btn-xs">Detay</a>
            </td>
        </tr>
    }
</table>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/SatisDetay.cshtml
@model List<KitapciApp.EntityLayer.SatısDetay>
@{
    ViewBag.Title = "Satış Detay Listele";
}

<h2>Satış Detay Listele</h2>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Kitap</th>
        <th>Adet</th>
        <th>Tutar</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@((item.Kitap == null)? "Null" : item.Kitap.Ad)</td>
            <td>@item.Adet</td>
            <td>@item.Tutar.ToString("C2")</td>
            <td>
                <a href="@Url.Action("Sil", new { id = item.Id})" class="btn btn-danger btn-xs">Sil</a>
            </td>
        </tr>
    }
</table>

<a href="@Url.Action("Listele")" class="btn btn-info">Geri</a>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/SatisEkle.cshtml
@model List<KitapciApp.EntityLayer.Kitap>
@{
    ViewBag.Title = "Satış Ekle";
}

<h2>Satış Ekle</h2>

<a href="@Url.Action("SepetGoster")" class="btn btn-primary">Sepete Git</a>

<br />
<br />

<table class="table">
    <tr>
        <th>Id</th>
        <th>Kitap Ad</th>
        <th>Tür</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Ad</td>
            <td>@item.Tur.Ad</td>
            <td>@item.Adet</td>
            <td>@item.Fiyat</td>
            <td>
                <a href="@Url.Action("SepeteEkle", new { id = item.Id})" class="btn btn-success btn-xs">Sepete Ekle</a>
            </td>
        </tr>
    }
</table>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/SepetGoster.cshtml
@model KitapciApp.EntityLayer.Satıs
@{
    ViewBag.Title = "Sepet Detay Listele";
}

<h2>Sepet Detay Listele</h2>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Kitap</th>
        <th>Adet</th>
        <th>Satış Durum</th>
        <th>Tutar</th>
        <th></th>
    </tr>
    @foreach (var item in Model.Detaylar)
    {
        <tr>
            <td>@((item.Kitap == null)? "Null" : item.Kitap.Ad)</td>
            <td>@item.Adet</td>
            <td>@item.Tutar.ToString("C2")</td>
            <td>
                @*<a href="@Url.Action("Sil", new { id = item.Id})" class="btn btn-danger btn-xs">Sil</a>*@
            </td>
        </tr>
    }
    @if (Model.Detaylar.Count == 0)
    {
        <tr>
            <td colspan="3"><span class="text-danger">Sepet Boş!</span></td>
        </tr>
    }
</table>

<a href="@Url.Action("SatisEkle")" class="btn btn-info">Geri</a>
@if (Model.Detaylar.Count != 0)
{
    <a href="@Url.Action("SatisTamamla")" class="btn btn-success">Tamamla</a>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Satis/Sil.cshtml
@model KitapciApp.EntityLayer.Satıs
@{
    ViewBag.Title = "Satış Sil";
}

<h2>Satış Sil</h2>

<hr />
<p>@Model.TarihSaat tarih-saatli satışı silmek istiyor musunuz?</p>

@using (Html.BeginForm("Sil", "Satis", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-10">
            <a href="@Url.Action("Listele")" class="btn btn-primary">Hayır</a>
            <button type="submit" class="btn btn-danger">Evet</button>
        </div>
    </div>
}