KitapciApp/KitapciApp.UI/Areas/Yonetim/Controllers/KitapController.cs
using KitapciApp.DataAccesLayer;
using KitapciApp.EntityLayer;
using KitapciApp.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapciApp.UI.Areas.Yonetim.Controllers
{
    [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
    public class KitapController : Controller
    {
        // GET: Yonetim/Kitap
        public ActionResult Listele()
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                return View(uow.KitapWork.GetAllWithTur());
            }
        }


        public ActionResult Ekle()
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Turler = new SelectList(uow.TurWork.GetAll(), "Id", "Ad");
            }
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Ekle(Kitap kitap)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KitapWork.Add(kitap);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
            }

            using (UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Turler = new SelectList(uow.TurWork.GetAll(), "Id", "Ad");
            }
            ModelState.AddModelError("", "Ekleme Başarısız.");
            return View(kitap);
        }


        public ActionResult Duzenle(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kitap kitap = uow.KitapWork.GetItem(id);
                    if (kitap != null)
                    {
                        ViewBag.Turler = new SelectList(uow.TurWork.GetAll(), "Id", "Ad");
                        return View(kitap);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Duzenle(int? id, Kitap kitap)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KitapWork.Update(kitap);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
            }
            using (UnitOfWork uow = new UnitOfWork())
            {
                ViewBag.Turler = new SelectList(uow.TurWork.GetAll(), "Id", "Ad");
            }
            ModelState.AddModelError("", "Düzenleme Yapılamadı.");
            return View(kitap);
        }


        public ActionResult Sil(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kitap kitap = uow.KitapWork.GetItem(id);
                    if (kitap != null)
                    {
                        return View(kitap);
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }
        [HttpPost, ValidateAntiForgeryToken, ActionName("Sil")]
        public ActionResult SilOnay(int? id)
        {
            if (id != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    Kitap kitap = uow.KitapWork.GetItem(id);
                    if (kitap != null)
                    {
                        uow.KitapWork.Remove(kitap);
                        uow.Save();
                        return RedirectToAction("Listele");
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
            }
            return RedirectToAction("Listele");
        }
    }
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kitap/Duzenle.cshtml
@model KitapciApp.EntityLayer.Kitap
@{
    ViewBag.Title = "Kitap Düzenle";
}

<h2>Kitap Düzenle</h2>

<br />
<br />

@using (Html.BeginForm("Duzenle", "Kitap", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.Ad, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Adet, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Yazar, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Yazar, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(x => x.Tur, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.DropDownListFor(x => x.TurId, ViewBag.Turler as SelectList, "Tür Seçiniz", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Fiyat, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <a href="@Url.Action("Listele")" class="btn btn-default">İptal</a>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </div>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kitap/Ekle.cshtml
@model KitapciApp.EntityLayer.Kitap
@{
    ViewBag.Title = "Kitap Ekle";
}

<h2>Kitap Ekle</h2>

<br />
<br />

@using (Html.BeginForm("Ekle", "Kitap", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.Ad, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Adet, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Tur, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.DropDownListFor(x => x.TurId, ViewBag.Turler as SelectList, "Tür Seçiniz", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Yazar, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Yazar, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Fiyat, new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <a href="@Url.Action("Listele")" class="btn btn-default">İptal</a>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </div>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kitap/Listele.cshtml
@model List<KitapciApp.EntityLayer.Kitap>
@{
    ViewBag.Title = "Kitap Listele";
}

<h2>Kitap Listesi</h2>

<a href="@Url.Action("Ekle")" class="btn btn-primary">Ekle</a>

<br />
<br />

<table class="table">
    <tr>
        <th>Id</th>
        <th>Ad</th>
        <th>Tür</th>
        <th>Yazar</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Ad</td>
            <td>@((item.Tur == null)?"NULL" : item.Tur.Ad)</td>
            <td>@item.Yazar</td>
            <td>@item.Adet</td>
            <td>@item.Fiyat.ToString("C2")</td>
            <td>
                <a href="@Url.Action("Sil", new { id = item.Id })" class="btn btn-danger btn-xs">Sil</a>
                <a href="@Url.Action("Duzenle", new { id = item.Id })" class="btn btn-primary btn-xs">Düzenle</a>
            </td>
        </tr>
    }
</table>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kitap/Sil.cshtml
@model KitapciApp.EntityLayer.Kitap
@{
    ViewBag.Title = "Kitap Sil";
}

<h2>Kitap Sil</h2>

<hr />
<p>@Model.Ad adlı kitabı silmek istiyor musunuz?</p>

@using (Html.BeginForm("Sil", "Kitap", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-10">
            <a href="@Url.Action("Listele")" class="btn btn-primary">Hayır</a>
            <button type="submit" class="btn btn-danger">Evet</button>
        </div>
    </div>
}