KitapciApp/KitapciApp.UI/Areas/Yonetim/Controllers/DashBoardController.cs
using KitapciApp.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KitapciApp.UI.Areas.Yonetim.Controllers
{
    [Kimlik]
    public class DashBoardController : Controller
    {
        // GET: Yonetim/DashBoard
        public ActionResult Index()
        {
            return View();
        }
    }
}

KitapciApp/KitapciApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <!--Bootsrap-->
    <link id="callCss" rel="stylesheet" href="/magaza/themes/bootshop/bootstrap.min.css" media="screen" />
    <link href="/magaza/themes/css/base.css" rel="stylesheet" media="screen" />
    <!-- Bootstrap style responsive -->
    <link href="/magaza/themes/css/bootstrap-responsive.min.css" rel="stylesheet" />
    <link href="/magaza/themes/css/font-awesome.css" rel="stylesheet" type="text/css">
    <!-- Google-code-prettify -->
    <link href="/magaza/themes/js/google-code-prettify/prettify.css" rel="stylesheet" />
    <style type="text/css" id="enject"></style>
</head>
<body>

    <div id="header">
        <div class="container">
            <div id="logoArea" class="navbar">
                <a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-inner">
                    <ul class="nav navbar-nav">
                        @if (Session["user"] != null && (Session["user"] as KitapciApp.EntityLayer.Kullanıcı).Yetki == KitapciApp.EntityLayer.Yetkiler.Uye)
                        {
                            <li><a href="@Url.Action("HomeView","Home")">Ana Ekran</a></li>
                            <li><a href="@Url.Action("SepetGoster", "Home")">Sepete Git</a></li>
                            <li><a href="@Url.Action("Kitaplarim", "Home")">Satın Alınanlar</a></li>
                        }
                        else if (Session["user"] != null && (Session["user"] as KitapciApp.EntityLayer.Kullanıcı).Yetki == KitapciApp.EntityLayer.Yetkiler.Yonetici)
                        {
                            <li><a href="@Url.Action("Index", "DashBoard")">Satın Alınanlar</a></li>
                        }
                        @if (Session["user"] != null)
                        {
                            <li class="item"><a href="@Url.Action("Logout","Home")">Çıkış</a></li>
                        }
                        else
                        {
                            <li class="item"><a style="color:white" href="@Url.Action("Login","Home")">Giriş</a></li>
                            <li class="item"><a style="color:white" href="@Url.Action("Ekle","Home")">Kayıt Ol</a></li>
                        }

                    </ul>
                </div>
            </div>
        </div>
    </div>

    <br />
    <span id="themesBtn"></span>
    <br />

    <div class="container body-content">
        @RenderBody()
    </div>

    <div id="footerSection" class="bottom">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <h5>BİLGİ</h5>
                    <a href="contact.html">İletişim</a>
                    <a href="register.html">Kayıt</a>
                </div>
                <div class="span3">
                    <h5>BİZİM TEKLİFLERİMİZ</h5>
                    <a href="#">Yeni Kitaplarımız</a>
                    <a href="#">Çok Satanlar</a>
                    <a href="#">Özel Teklifler</a>
                    <a href="#">Üreticiler</a>
                    <a href="#">Tedarikçiler</a>
                </div>
                <div id="socialMedia" class="span3 pull-right">
                    <h5>SOCIAL MEDIA </h5>
                    <a href="#"><img width="60" height="60" src="/magaza/themes/images/facebook.png" title="facebook" alt="facebook" /></a>
                    <a href="#"><img width="60" height="60" src="/magaza/themes/images/twitter.png" title="twitter" alt="twitter" /></a>
                    <a href="#"><img width="60" height="60" src="/magaza/themes/images/youtube.png" title="youtube" alt="youtube" /></a>
                </div>
            </div>
            <p class="pull-right">&copy; Bootshop</p>
        </div><!-- Container End -->
    </div>

    <script src="/magaza/themes/js/jquery.js" type="text/javascript"></script>
    <script src="/magaza/themes/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/magaza/themes/js/google-code-prettify/prettify.js"></script>
    <script src="/magaza/themes/js/bootshop.js"></script>
    <script src="/magaza/themes/js/jquery.lightbox-0.5.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>