KitapciApp/KitapciApp.UI/Areas/Yonetim/Controllers/KullaniciController.cs
using KitapciApp.DataAccesLayer;
using KitapciApp.EntityLayer;
using KitapciApp.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace KitapciApp.UI.Areas.Yonetim.Controllers
{
    public class KullaniciController : Controller
    {
        // GET: Yonetim/Kullanici
        public ActionResult Login()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("index", "DashBoard");
            }
        }
        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult Login(Kullanıcı kullanıcı)
        {
            if (kullanıcı != null)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    if (uow.KullanıcıWork.Login(kullanıcı.EPosta.ToLower(), kullanıcı.Parola))
                    {
                        Kullanıcı user = uow.KullanıcıWork.GetItem(kullanıcı.EPosta);
                        if (user.Yetki == Yetkiler.Yonetici)
                        {
                            Session["user"] = user;
                            return RedirectToAction("index", "DashBoard");
                        }
                    }
                } 
            }
            ModelState.AddModelError("", "Kullanıcı adı veya parola hatalı.");
            return View(kullanıcı);
        }


        public ActionResult Logout()
        {
            if(Session["user"] != null)
            {
                Session.Remove("user");
            }
            return RedirectToAction("Login");
        }


        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Listele()
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
                return View(uow.KullanıcıWork.GetAll());
            }
        }


        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost,ValidateAntiForgeryToken]
        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Ekle(Kullanıcı kullanıcı)
        {
            if (ModelState.IsValid)
            {
                using(UnitOfWork uow = new UnitOfWork())
                {
                    uow.KullanıcıWork.Add(kullanıcı);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
            }
            return View(kullanıcı);
        }


        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Duzenle(string eposta)
        {
            using(UnitOfWork uow = new UnitOfWork())
            {
                Kullanıcı kullanıcı = uow.KullanıcıWork.GetItem(eposta);
                if(kullanıcı != null)
                {
                    return View(kullanıcı);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
        [HttpPost,ValidateAntiForgeryToken]
        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Duzenle(Kullanıcı kullanıcı)
        {
            if (ModelState.IsValid)
            {
                using (UnitOfWork uow = new UnitOfWork())
                {
                    uow.KullanıcıWork.Update(kullanıcı);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
            }
            return View(kullanıcı);
        }


        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult Sil(string eposta)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                Kullanıcı kullanıcı = uow.KullanıcıWork.GetItem(eposta);
                if (kullanıcı != null)
                {
                    return View(kullanıcı);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
        [HttpPost,ValidateAntiForgeryToken,ActionName("Sil")]
        [Kimlik, Yetki(Yetki = Yetkiler.Yonetici)]
        public ActionResult SilOnay(string eposta, Kullanıcı model)
        {
            using (UnitOfWork uow = new UnitOfWork())
            {
                Kullanıcı kullanıcı = uow.KullanıcıWork.GetItem(model.EPosta);
                if (kullanıcı != null)
                {
                    uow.KullanıcıWork.Remove(kullanıcı);
                    uow.Save();
                    return RedirectToAction("Listele");
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }
    }
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kullanici/Duzenle.cshtml
@model KitapciApp.EntityLayer.Kullanıcı
@{
    ViewBag.Title = "Kullanıcı Düzenle";
}

<h2>Kullanıcı Düzenle</h2>

<br />
<br />

@using (Html.BeginForm("Duzenle", "Kullanici", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.EPosta, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.EPosta, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Ad, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Soyad, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Parola, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Parola, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Yetki, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x => x.Yetki, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <a href="@Url.Action("Listele")" class="btn btn-default">İptal</a>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </div>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kullanici/Ekle.cshtml
@model KitapciApp.EntityLayer.Kullanıcı
@{
    ViewBag.Title = "Kullanıcı Ekle";
}

<h2>Kullanıcı Ekle</h2>

<br />
<br />

@using (Html.BeginForm("Ekle", "Kullanici", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(x => x.EPosta, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.EPosta, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Ad, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Soyad, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Parola, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(x => x.Parola, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.Yetki, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EnumDropDownListFor(x=>x.Yetki, new {@class="form-control"})
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            <a href="@Url.Action("Listele")" class="btn btn-default">İptal</a>
            <button type="submit" class="btn btn-primary">Kaydet</button>
        </div>
    </div>
}

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kullanici/Listele.cshtml
@model List<KitapciApp.EntityLayer.Kullanıcı>
@{
    ViewBag.Title = "Listele";
}

<h2>Listele</h2>

<a href="@Url.Action("Ekle")" class="btn btn-primary">Ekle</a>

<br />
<br />

<table class="table">
    <tr>
        <th>EPosta</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Yetki</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EPosta</td>
            <td>@item.Ad</td>
            <td>@item.Soyad</td>
            <td>@item.Yetki</td>
            <td>
                <a href="@Url.Action("Sil", new { eposta = item.EPosta})" class="btn btn-danger btn-xs">Sil</a>
                <a href="@Url.Action("Duzenle", new { eposta = item.EPosta})" class="btn btn-info btn-xs">Düzenle</a>
            </td>
        </tr>
    }
</table>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kullanici/Login.cshtml
@model KitapciApp.EntityLayer.Kullanıcı
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div>
        <h2>Lütfen Giriş Yapınız</h2>
        <hr />
        @using (Html.BeginForm("Login", "Kullanici", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(x => x.EPosta, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(x => x.EPosta, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.EPosta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Parola, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(x => x.Parola, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Parola, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary">Giriş</button>
                </div>
            </div>
        }


    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

KitapciApp/KitapciApp.UI/Areas/Yonetim/Views/Kullanici/Sil.cshtml
@model KitapciApp.EntityLayer.Kullanıcı
@{
    ViewBag.Title = "Kullanıcı Sil";
}

<h2>Kullanıcı Sil</h2>

<hr />
<p>@Model.EPosta eposta adresli kullanıcıyı silmek istiyor musunuz?</p>

@using (Html.BeginForm("Sil", "Kullanici", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x=>x.EPosta)
    <div class="form-group">
        <div class="col-md-10">
            <a href="@Url.Action("Listele")" class="btn btn-primary">Hayır</a>
            <button type="submit" class="btn btn-danger">Evet</button>
        </div>
    </div>
}